# Node.js with Next.js & React
# Build a Node.js project that uses Next.js & React.
# Add steps that analyze code, save build artifacts, deploy, and more:

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: custom
    customCommand: 'install --timing'
    customRegistry: useNpmrc
    verbose: true

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: 'run build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: CopyFiles@2
  inputs:
    contents: _buildOutput\**
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
  condition: succeededOrFailed()