export default {
  env: process.env.NODE_ENV,
  mode: process.env.MODE,
  MANAGEMENT_API_URL: '#{MANAGEMENT_API_URL}#',
  MANAGEMENT_API_VERSION: '#{MANAGEMENT_API_VERSION}#',
  PLATFORM_API_URL: '#{PLATFORM_API_URL}#',
  REDIRECT_URL: '#{REDIRECT_URL}#',
  EDIT_PROFILE_REDIRECT_URL: '#{EDIT_PROFILE_REDIRECT_URL}#'
}
